defaultRules:
  create: true

alertmanager:
  enabled: false

grafana:
  enabled: true
  adminPassword: "${admin_password}"
  service:
    type: LoadBalancer
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    storageSpec: {}
    resources:
      requests:
        cpu: 100m
        memory: 256Mi