applications:
  - name: django-app
    namespace: argocd
    project: default
    source:
      repoURL: ${github_url}
      path: ${helm_chart_path}
      targetRevision: ${github_main_branch}
      helm:
        valueFiles:
          - values.yaml
        # Додаємо параметри, які перекриють стандартні налаштування в Helm-чарті
        values: |
          config:
            db_host: "olga-db.cxqkcoao20z1.us-west-2.rds.amazonaws.com"
            db_name: "${db_name}"
            db_user: "${db_user}"
            db_pass: "${db_password}"
            db_port: "5432"
    destination:
      server: https://kubernetes.default.svc
      namespace: jenkins
    syncPolicy:
      automated:
        prune: true
        selfHeal: true

repositories:
  - name: django-app-repo
    url: ${github_url}
    username: ${github_username}
    password: ${github_pat}
    type: git

repoConfig:
  insecure: "true"
  enableLfs: "true"